#!/usr/bin/env node
/**
 * Clawd — one-shot stack installer (Grok Build style).
 *
 * Installs:
 *   • RH / Cheshire skill pack (23 skills) → ~/.clawdbot/skills + ~/.agents/skills
 *   • Env template with CLAWDBOT_SKILLS_DIR, RH hooks
 *   • Optional: Go clawdbot binary, automaton-main deps, birth skill seeds
 *
 * Usage:
 *   npm i -g clawd-go
 *   clawdbot install
 *   clawd install
 *   npx clawd-go install
 *   curl -fsSL https://raw.githubusercontent.com/Solizardking/Zero-Bruh/main/install-npm.sh | bash
 */
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import {
  inspectPack,
  listSkillIds,
  PACKAGE_ROOT,
  SKILLS_DIR,
  loadPackIndex,
} from "./skill-pack.mjs";
import { playInstallPumpTape } from "./pump-tape.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

const CYAN = "\x1b[36m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const BOLD = "\x1b[1m";
const RESET = "\x1b[0m";

function info(msg) {
  console.log(`${CYAN}  ▶${RESET} ${msg}`);
}
function ok(msg) {
  console.log(`${GREEN}  ✓${RESET} ${msg}`);
}
function warn(msg) {
  console.log(`${YELLOW}  ⚠${RESET} ${msg}`);
}
function die(msg) {
  console.error(`${RED}  ✗ ERROR:${RESET} ${msg}`);
  process.exit(1);
}

function parseArgs(argv) {
  const flags = {
    skipGo: false,
    skipBirth: false,
    skipAutomaton: false,
    force: false,
    dir: "",
    help: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--help" || a === "-h") flags.help = true;
    else if (a === "--skip-go") flags.skipGo = true;
    else if (a === "--skip-birth") flags.skipBirth = true;
    else if (a === "--skip-automaton") flags.skipAutomaton = true;
    else if (a === "--force") flags.force = true;
    else if (a === "--dir" || a === "--install-dir") {
      flags.dir = argv[i + 1] || "";
      i += 1;
    } else if (a === "install" || a === "oneshot") {
      /* subcommand alias */
    } else if (a.startsWith("-")) {
      die(`Unknown flag: ${a}`);
    }
  }
  return flags;
}

function hasCmd(name) {
  const r = spawnSync(name, ["--version"], { stdio: "ignore", shell: false });
  return r.status === 0 || r.error === undefined && (r.status === 0 || r.status === null);
}

function which(name) {
  const r = spawnSync(process.platform === "win32" ? "where" : "command", 
    process.platform === "win32" ? [name] : ["-v", name],
    { encoding: "utf8", shell: false },
  );
  if (r.status !== 0) return "";
  return String(r.stdout || "").trim().split("\n")[0] || "";
}

function commandExists(cmd) {
  try {
    const r = spawnSync(
      process.platform === "win32" ? "where" : "sh",
      process.platform === "win32" ? [cmd] : ["-c", `command -v ${cmd}`],
      { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    );
    return r.status === 0 && String(r.stdout || "").trim().length > 0;
  } catch {
    return false;
  }
}

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function appendEnvIfMissing(envPath, key, value) {
  if (!value) return false;
  let body = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  if (new RegExp(`^${key}=`, "m").test(body)) return false;
  if (body && !body.endsWith("\n")) body += "\n";
  body += `${key}=${value}\n`;
  writeFileSync(envPath, body, { mode: 0o600 });
  return true;
}

function writeEnvTemplate(envPath, values) {
  if (existsSync(envPath) && !values.force) {
    let added = 0;
    for (const [k, v] of Object.entries(values.entries)) {
      if (appendEnvIfMissing(envPath, k, v)) added += 1;
    }
    return { created: false, added };
  }
  const lines = [
    "# ════════════════════════════════════════════════════════════════════",
    "# Clawd Bot / clawdbot-go — generated by oneshot npm installer",
    "# ════════════════════════════════════════════════════════════════════",
    "",
    `# Install home: ${values.installDir}`,
    `CLAWDBOT_HOME=${values.installDir}`,
    `CLAWDBOT_SKILLS_DIR=${values.skillsDir}`,
    `CLAWDBOT_MERGE_BUNDLED_SKILLS=1`,
    "",
    "# Robinhood Chain (4663) — set for launch/deploy/trade",
    "# BLOCKSCOUT_API_KEY=proapi_…",
    "# RH_RPC_URL=https://your-private-rpc",
    "",
    "# Free AI via zkrouter (optional key from install API)",
    "ZKROUTER_BASE_URL=https://clawdrouter-zk.fly.dev/v1",
    "",
    "# Product surfaces",
    "CLAWD_TERMINAL_URL=https://cheshireterminal.ai",
    "FUNPUMP_URL=https://funpump.ai",
    "",
  ];
  for (const [k, v] of Object.entries(values.entries)) {
    if (v && !lines.some((l) => l.startsWith(`${k}=`))) {
      lines.push(`${k}=${v}`);
    }
  }
  lines.push("");
  writeFileSync(envPath, lines.join("\n"), { mode: 0o600 });
  return { created: true, added: Object.keys(values.entries).length };
}

/**
 * Skills-only prepackage (used by npm postinstall + `npx clawdbot-go skills-install`).
 * Copies the full bundled skills tree and links every SKILL.md into agent roots.
 */
export function installSkillPackOnly({ installDir, force = false } = {}) {
  return installSkillPack({
    installDir: installDir || join(homedir(), ".clawdbot"),
    force,
  });
}

/**
 * Copy skill pack into installDir/skills and symlink each skill into agents dirs.
 * Installs pack-index skills plus any extra on-disk SKILL.md directories.
 */
function installSkillPack({ installDir, force }) {
  const destSkills = join(installDir, "skills");
  ensureDir(installDir);

  if (existsSync(destSkills) && force) {
    rmSync(destSkills, { recursive: true, force: true });
  }

  if (!existsSync(SKILLS_DIR)) {
    die(`Bundled skills missing at ${SKILLS_DIR}`);
  }

  // Prefer full tree copy so pack-index + catalog ship together.
  // Do NOT filter on "node_modules" in the absolute path — when installed from
  // npm the package lives at …/node_modules/clawdbot-go/skills and a naive
  // includes("node_modules") filter would drop every file.
  ensureDir(destSkills);
  cpSync(SKILLS_DIR, destSkills, {
    recursive: true,
    force: true,
  });

  const pack = loadPackIndex();
  const fromIndex = listSkillIds();
  // Union pack-index + every directory that actually has SKILL.md
  const onDisk = readdirSync(destSkills)
    .filter((name) => {
      const dir = join(destSkills, name);
      try {
        return statSync(dir).isDirectory() && existsSync(join(dir, "SKILL.md"));
      } catch {
        return false;
      }
    })
    .sort();
  const ids = [...new Set([...fromIndex, ...onDisk])];

  const agentRoots = [
    join(homedir(), ".agents", "skills"),
    join(homedir(), ".claude", "skills"),
    join(homedir(), ".codex", "skills"),
  ];

  // Link into agent hosts in one shell batch — Node fs.equivalent can abort on
  // macOS multi-volume paths; per-skill spawnSync is also slow.
  let linked = 0;
  if (process.env.CLAWDBOT_SKIP_AGENT_LINKS !== "1") {
    const script = [
      "set +e",
      ...agentRoots.map((root) => `mkdir -p ${JSON.stringify(root)}`),
      ...agentRoots.flatMap((root) =>
        ids.map((id) => {
          const src = join(destSkills, id);
          const dst = join(root, id);
          return `if [ -d ${JSON.stringify(src)} ]; then ln -sfn ${JSON.stringify(src)} ${JSON.stringify(dst)} && echo linked; fi`;
        }),
      ),
    ].join("\n");
    const batch = spawnSync("bash", ["-c", script], {
      encoding: "utf8",
      timeout: 30_000,
    });
    if (batch.status === 0 || batch.stdout) {
      linked = String(batch.stdout || "")
        .split("\n")
        .filter((l) => l.trim() === "linked").length;
    }
  }

  try {
    writeFileSync(
      join(destSkills, ".clawdbot-prepackaged.json"),
      JSON.stringify(
        {
          prepackagedAt: new Date().toISOString(),
          packId: pack.id,
          skillCount: ids.length,
          packIndexCount: fromIndex.length,
          skills: ids,
          productHost: pack.productHost || "https://funpump.ai",
          terminalHost: pack.terminalHost || "https://cheshireterminal.ai",
          agentHub: pack.agentHub || "https://cheshireterminal.ai/agents",
          forgeHost: pack.forgeHost || "https://cheshireterminal.ai/agents/forge",
          zeroClawdHost: pack.zeroClawdHost || "https://cheshireterminal.ai/zeroclawd",
          agentsNpm: pack.agentsNpm || "https://www.npmjs.com/package/cheshire-terminal-agents",
          agentsRepo: pack.agentsRepo || "https://github.com/Solizardking/Cheshire-Terminal-Agents",
          skillHubRepo: pack.skillHubRepo || "https://github.com/Solizardking/skillhub-main",
        },
        null,
        2,
      ),
    );
  } catch {
    /* non-fatal */
  }

  return {
    skillsDir: destSkills,
    skillCount: ids.length,
    packId: pack.id,
    linked,
    agentRoots,
  };
}

function installAutomaton({ packageRoot, skip }) {
  if (skip) return { skipped: true };
  const autoDir = join(packageRoot, "automaton-main");
  if (!existsSync(join(autoDir, "package.json"))) {
    return { skipped: true, reason: "automaton-main not in package" };
  }
  if (!commandExists("npm")) {
    return { skipped: true, reason: "npm not found" };
  }
  info("Installing automaton-main dependencies...");
  const r = spawnSync("npm", ["install", "--legacy-peer-deps", "--ignore-scripts"], {
    cwd: autoDir,
    stdio: "inherit",
    env: process.env,
  });
  return { ok: r.status === 0, status: r.status, dir: autoDir };
}

function tryBuildGoBinary({ packageRoot, installDir, skip }) {
  if (skip) return { skipped: true };
  if (!commandExists("go")) {
    warn("Go not found — skip clawdbot binary (install Go then: go build -o ~/.clawdbot/bin/clawdbot ./cmd/clawdbot)");
    return { skipped: true, reason: "go not found" };
  }
  const cmdDir = join(packageRoot, "cmd", "clawdbot");
  if (!existsSync(cmdDir)) {
    warn("cmd/clawdbot not in this package — use full git install for binary:");
    warn("  curl -fsSL https://raw.githubusercontent.com/Solizardking/Zero-Bruh/main/install.sh | bash");
    return { skipped: true, reason: "go sources not shipped in npm pack" };
  }
  const binDir = join(installDir, "bin");
  ensureDir(binDir);
  const out = join(binDir, "clawdbot");
  info("Building clawdbot Go binary...");
  const r = spawnSync(
    "go",
    ["build", "-buildvcs=false", "-trimpath", "-ldflags=-s -w", "-o", out, "./cmd/clawdbot/"],
    { cwd: packageRoot, stdio: "inherit", env: process.env },
  );
  if (r.status !== 0) {
    warn("Go build failed");
    return { ok: false, status: r.status };
  }
  const localBin = join(homedir(), ".local", "bin");
  ensureDir(localBin);
  try {
    copyFileSync(out, join(localBin, "clawdbot"));
  } catch {
    /* ignore */
  }
  ok(`Binary: ${out}`);
  return { ok: true, path: out };
}

function seedBirthSkills({ skip }) {
  if (skip) return { skipped: true };
  if (!commandExists("npx")) {
    return { skipped: true, reason: "npx not found" };
  }
  // Default to the interactive `skills add` picker so the operator chooses
  // which skills/agents to install. Fall back to --all (install everything,
  // no prompt) when there's no real TTY to drive a prompt from, or when the
  // operator explicitly asks via CLAWDBOT_SKILLS_ALL=1.
  const useAll = process.env.CLAWDBOT_SKILLS_ALL === "1" || !process.stdin.isTTY;
  if (useAll && process.stdin.isTTY === false) {
    info("No interactive terminal detected; installing all birth skills non-interactively.");
  }
  const extraArgs = useAll ? ["--all"] : [];
  info(
    useAll
      ? "Seeding birth skills (Solizardking/skills + Go skills)..."
      : "Choose birth skills to seed (Solizardking/skills + Go skills)...",
  );
  const sources = [
    ["skills", "add", "https://github.com/Solizardking/skills", ...extraArgs],
    ["skills", "add", "https://github.com/samber/cc-skills-golang", ...extraArgs],
  ];
  const results = [];
  for (const args of sources) {
    const r = spawnSync("npx", ["--yes", ...args], {
      stdio: "inherit",
      env: process.env,
      timeout: useAll ? 120_000 : 600_000,
    });
    results.push({ args, status: r.status });
    if (r.status !== 0) warn(`Birth seed failed: npx ${args.join(" ")}`);
  }
  return { ok: results.every((x) => x.status === 0), results };
}

function printBanner() {
  console.log(`${CYAN}`);
  console.log(`    ██████╗██╗      █████╗ ██╗    ██╗██████╗`);
  console.log(`   ██╔════╝██║     ██╔══██╗██║    ██║██╔══██╗`);
  console.log(`   ██║     ██║     ███████║██║ █╗ ██║██║  ██║`);
  console.log(`   ██║     ██║     ██╔══██║██║███╗██║██║  ██║`);
  console.log(`   ╚██████╗███████╗██║  ██║╚███╔███╔╝██████╔╝`);
  console.log(`    ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═════╝`);
  console.log(`${RESET}`);
  console.log(`${BOLD}  🦞 Clawd — one-shot stack (npm)${RESET}`);
  console.log(`  Skills · Agents · Packages · Solana + Robinhood omni`);
  console.log();
}

export function runOneshot(options = {}) {
  const flags = {
    skipGo: Boolean(options.skipGo),
    skipBirth: Boolean(options.skipBirth),
    skipAutomaton: Boolean(options.skipAutomaton),
    force: Boolean(options.force),
    dir: options.dir || process.env.CLAWDBOT_INSTALL_DIR || join(homedir(), ".clawdbot"),
  };

  printBanner();
  playInstallPumpTape();

  const inspect = inspectPack();
  if (!inspect.ok) {
    warn(`Pack inspection issues: ${inspect.missing.join(", ")}`);
  } else {
    ok(`Skill pack OK — ${inspect.skillCount} skills (${inspect.packId})`);
  }

  const installDir = resolve(flags.dir);
  ensureDir(installDir);
  info(`Install home: ${installDir}`);

  const skillResult = installSkillPack({ installDir, force: flags.force });
  ok(`Skills installed → ${skillResult.skillsDir} (${skillResult.skillCount})`);
  ok(`Linked into agent skill dirs (${skillResult.linked} links)`);

  const envPath = join(installDir, ".env");
  const envResult = writeEnvTemplate(envPath, {
    force: flags.force,
    installDir,
    skillsDir: skillResult.skillsDir,
    entries: {
      CLAWDBOT_HOME: installDir,
      CLAWDBOT_SKILLS_DIR: skillResult.skillsDir,
      CLAWDBOT_MERGE_BUNDLED_SKILLS: "1",
    },
  });
  if (envResult.created) ok(`.env written → ${envPath}`);
  else ok(`.env updated (${envResult.added} keys) → ${envPath}`);

  // Symlink ~/.clawdbot if installDir is custom
  const defaultHome = join(homedir(), ".clawdbot");
  if (installDir !== defaultHome) {
    try {
      if (!existsSync(defaultHome)) {
        symlinkSync(installDir, defaultHome, "dir");
        ok(`Linked ${defaultHome} → ${installDir}`);
      }
    } catch {
      /* ignore */
    }
  }

  const auto = installAutomaton({ packageRoot: PACKAGE_ROOT, skip: flags.skipAutomaton });
  if (auto.ok) ok(`automaton-main deps at ${auto.dir}`);
  else if (auto.skipped) info(`automaton: skipped (${auto.reason || "flag"})`);

  const go = tryBuildGoBinary({
    packageRoot: PACKAGE_ROOT,
    installDir,
    skip: flags.skipGo,
  });

  const birth = seedBirthSkills({ skip: flags.skipBirth });
  if (birth.ok) ok("Birth skill seeds complete");
  else if (birth.skipped) info(`Birth seeds skipped (${birth.reason || "flag"})`);

  // Write install receipt
  const receipt = {
    installedAt: new Date().toISOString(),
    packageRoot: PACKAGE_ROOT,
    installDir,
    skillsDir: skillResult.skillsDir,
    skillCount: skillResult.skillCount,
    packId: skillResult.packId,
    go: go.ok ? go.path : null,
    productHost: "https://funpump.ai",
    terminalHost: "https://cheshireterminal.ai",
    agentHub: "https://cheshireterminal.ai/agents",
    forgeHost: "https://cheshireterminal.ai/agents/forge",
    zeroClawdHost: "https://cheshireterminal.ai/zeroclawd",
    agentsNpm: "https://www.npmjs.com/package/cheshire-terminal-agents",
    agentsRepo: "https://github.com/Solizardking/Cheshire-Terminal-Agents",
    skillHubRepo: "https://github.com/Solizardking/skillhub-main",
    oneShot: "curl -fsSL https://raw.githubusercontent.com/Solizardking/Zero-Bruh/main/install-npm.sh | bash",
  };
  writeFileSync(join(installDir, "oneshot-receipt.json"), JSON.stringify(receipt, null, 2));

  console.log();
  console.log(`${GREEN}${BOLD}  ══════════════════════════════════════════${RESET}`);
  console.log(`${GREEN}${BOLD}  🦞 Clawd stack installed (npm oneshot)${RESET}`);
  console.log(`${GREEN}${BOLD}  ══════════════════════════════════════════${RESET}`);
  console.log();
  console.log(`  ${BOLD}Pump.fun live:${RESET} https://solgpt.us/pump`);
  console.log(`  ${BOLD}Get started:${RESET}`);
  console.log(`  ${CYAN}export CLAWDBOT_SKILLS_DIR="${skillResult.skillsDir}"${RESET}`);
  console.log(`  ${CYAN}source ${envPath}${RESET}`);
  console.log(`  ${CYAN}npx clawdbot-go skills${RESET}              # list RH pack`);
  console.log(`  ${CYAN}clawdbot catalog skills${RESET}             # if Go binary present`);
  console.log(`  ${CYAN}# Set BLOCKSCOUT_API_KEY + RH_RPC_URL for RH 4663${RESET}`);
  console.log();
  console.log(`  ${BOLD}Surfaces:${RESET}`);
  console.log(`    Clawd        https://cheshireterminal.ai/zeroclawd`);
  console.log(`    Agent hub    https://cheshireterminal.ai/agents`);
  console.log(`    Agent forge  https://cheshireterminal.ai/agents/forge`);
  console.log(`    FunPump      https://funpump.ai`);
  console.log(`  ${BOLD}Open agents:${RESET}`);
  console.log(`    npm          https://www.npmjs.com/package/cheshire-terminal-agents`);
  console.log(`    GitHub       https://github.com/Solizardking/Cheshire-Terminal-Agents`);
  console.log(`    SkillHub     https://github.com/Solizardking/skillhub-main`);
  console.log(`  ${BOLD}Skills:${RESET}   ${skillResult.skillCount} in ${skillResult.skillsDir}`);
  console.log(`  ${BOLD}Full Go:${RESET}  curl -fsSL https://raw.githubusercontent.com/Solizardking/Zero-Bruh/main/install.sh | bash`);
  console.log(`  ${BOLD}npm package:${RESET} npm i -g clawd-go && clawdbot install`);
  console.log(`  ${BOLD}Agents SDK:${RESET}  npm i cheshire-terminal-agents`);
  console.log(`  ${BOLD}SkillHub:${RESET}     npx github:Solizardking/skills install cheshire-terminal-agents --force`);
  console.log();
  console.log(`  🦞 $CLAWD :: Droids Lead The Way`);
  console.log();

  return receipt;
}

function printHelp() {
  console.log(`Clawd oneshot — install the skill/agent stack

Usage:
  npm i -g clawd-go
  clawdbot install

  clawd install
  npx clawd-go install
  npx clawdbot-go install
  npx clawd-go oneshot [--dir ~/.clawdbot] [--skip-go] [--skip-birth] [--skip-automaton] [--force]
  npx clawd-go skills-install          # skills only (same as default npm postinstall)

  # Prepackage ALL bundled skills on npm install (default postinstall):
  npm i clawd-go
  # Full stack in postinstall:
  CLAWDBOT_ONESHOT=1 npm i -g clawd-go

  curl -fsSL https://raw.githubusercontent.com/Solizardking/Zero-Bruh/main/install-npm.sh | bash

  Install prints a live Pump.fun launch tape from https://solgpt.us/pump.
  Skip: CLAWDBOT_SKIP_PUMP_TAPE=1

Commands:
  install | oneshot   Full stack install (default)
  skills-install      Prepackage skills only → ~/.clawdbot/skills + agent roots
  skills              List skill ids from pack-index
  inspect             Validate pack SKILL.md files
  skills-dir          Print absolute skills directory
  help                This message
`);
}

export function main(argv = process.argv.slice(2)) {
  const cmd = argv[0];
  if (!cmd || cmd === "help" || cmd === "--help" || cmd === "-h") {
    if (cmd === "help" || cmd === "--help" || cmd === "-h") {
      printHelp();
      return;
    }
  }

  if (cmd === "skills" || cmd === "list") {
    console.log(listSkillIds().join("\n"));
    return;
  }
  if (cmd === "inspect") {
    console.log(JSON.stringify(inspectPack(), null, 2));
    return;
  }
  if (cmd === "skills-dir") {
    console.log(SKILLS_DIR);
    return;
  }
  if (cmd === "skills-install" || cmd === "prepackage-skills") {
    const flags = parseArgs(argv.slice(1));
    const installDir =
      flags.dir || process.env.CLAWDBOT_INSTALL_DIR || join(homedir(), ".clawdbot");
    const result = installSkillPackOnly({ installDir, force: flags.force });
    console.log(
      JSON.stringify(
        {
          ok: true,
          skillsDir: result.skillsDir,
          skillCount: result.skillCount,
          linked: result.linked,
          packId: result.packId,
        },
        null,
        2,
      ),
    );
    return;
  }

  const flags = parseArgs(argv);
  if (flags.help) {
    printHelp();
    return;
  }
  runOneshot(flags);
}

const isMain =
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  main();
}
